source 'https://rubygems.org'

gem 'jekyll', '~> 4.2'
gem 'jekyll-feed', '~> 0.16'
gem 'jekyll-seo-tag', '~> 2.7'
gem 'jekyll-sitemap', '~> 1.4'
gem 'jekyll-paginate', '~> 1.1'
gem 'jekyll-archives', '~> 2.2'
gem 'jekyll-toc', '~> 0.17'
gem 'jekyll-redirect-from', '~> 0.14'
gem 'jekyll-sass-converter', '~> 2.1'
gem 'jekyll-avatar', '~> 0.7'
gem 'jekyll-remote-theme', '~> 0.5'
gem 'kramdown', '~> 2.3'
gem 'sassc', '~> 2.4'
gem 'rouge', '~> 3.27'
